http:
  middlewares:
    SslHeader:
      headers:
        frameDeny: true
        accessControlAllowMethods:
          - "GET"
          - "OPTIONS"
          - "PUT"
        accessControlAllowOriginList:
          - "origin-list-or-null"
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline'"
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "same-origin"
        permissionsPolicy: "vibrate 'self'"
        stsSeconds: 315360000
    portainer-csp:
      headers:
        frameDeny: true
        accessControlAllowMethods:
          - "GET"
          - "OPTIONS"
          - "PUT"
        accessControlAllowOriginList:
          - "origin-list-or-null"
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; font-src 'self' data:; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "same-origin"
        permissionsPolicy: "vibrate 'self'"
        stsSeconds: 315360000

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true
      curvePreferences: ["CurveP521", "CurveP384"]
      cipherSuites: [
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
      ]
